### ISSUE TITLE
Chaining $getByRole generates the wrong locator

### ISSUE THREAD

**Issue by arjay00** [DanteUkraine/playwright-elements#36]
**Describe the bug**
Chaining of `$getByRole` inside the subElements that contains { name } generates the wrong locator, it basically copies the name from the `subElement` property.

**To Reproduce**
1. I created `$getByRole('table', { name: 'Users'  }).subElements({ row: $('tbody').$getByRole('row', { name: 'Something' }) })`
3. It produces `getByRole('table', { name: 'Something' }).locator('tbody').getByRole('row', { name: 'Something' })`

**Expected behavior**
Should generate `getByRole('table', { name: 'Users' }).locator('tbody').getByRole('row', { name: 'Something' })`

**Screenshots**
None

**Environment (please complete the following information):**
 - OS: Windows
 - Playwright Version: 1.36.2

**Additional context**
None

**Comment by DanteUkraine** [comment]
Thanks, will fix it in next version.

**Comment by DanteUkraine** [comment]
Fix will be included in v.1.8.3

**Comment by DanteUkraine** [comment]
Fix will be included in v.1.8.3

**Comment by arjay00** [comment]
Thank you @DanteUkraine, appreciate it. 😁
