### ISSUE TITLE
Salesforce Page Objects

### ISSUE THREAD

**Issue by PavanMudigondaTR** [DanteUkraine/playwright-elements#55]
**Is your feature request related to a problem? Please describe.**
Are you able to support salesforce page objects if possible ? https://www.npmjs.com/package/salesforce-pageobjects
**Describe the solution you'd like**
Ability to use salesforce page objects in playwright using https://www.npmjs.com/package/salesforce-pageobjects

**Describe alternatives you've considered**
webdriverio with UTAM for salesforce
**Additional context**

**Comment by DanteUkraine** [comment]
> **Is your feature request related to a problem? Please describe.** Are you able to support salesforce page objects if possible ? https://www.npmjs.com/package/salesforce-pageobjects **Describe the solution you'd like** Ability to use salesforce page objects in playwright using https://www.npmjs.com/package/salesforce-pageobjects
> 
> **Describe alternatives you've considered** webdriverio with UTAM for salesforce **Additional context** Add any other context or screenshots about the feature request here.

Sounds like interesting idea, I will try add support for salesforce page objects in next version.

**Comment by PavanMudigondaTR** [comment]
> > **Is your feature request related to a problem? Please describe.** Are you able to support salesforce page objects if possible ? https://www.npmjs.com/package/salesforce-pageobjects **Describe the solution you'd like** Ability to use salesforce page objects in playwright using https://www.npmjs.com/package/salesforce-pageobjects
> > **Describe alternatives you've considered** webdriverio with UTAM for salesforce **Additional context** Add any other context or screenshots about the feature request here.
> 
> Sounds like interesting idea, I will try add support for salesforce page objects in next version.

Anything i can do to contribute to this ?

**Comment by DanteUkraine** [comment]
> > > **Is your feature request related to a problem? Please describe.** Are you able to support salesforce page objects if possible ? https://www.npmjs.com/package/salesforce-pageobjects **Describe the solution you'd like** Ability to use salesforce page objects in playwright using https://www.npmjs.com/package/salesforce-pageobjects
> > > **Describe alternatives you've considered** webdriverio with UTAM for salesforce **Additional context** Add any other context or screenshots about the feature request here.
> > 
> > 
> > Sounds like interesting idea, I will try add support for salesforce page objects in next version.
> 
> Anything i can do to contribute to this ?

Not yet. I will start work on it soon.

**Comment by DanteUkraine** [comment]
> > > **Is your feature request related to a problem? Please describe.** Are you able to support salesforce page objects if possible ? https://www.npmjs.com/package/salesforce-pageobjects **Describe the solution you'd like** Ability to use salesforce page objects in playwright using https://www.npmjs.com/package/salesforce-pageobjects
> > > **Describe alternatives you've considered** webdriverio with UTAM for salesforce **Additional context** Add any other context or screenshots about the feature request here.
> > 
> > 
> > Sounds like interesting idea, I will try add support for salesforce page objects in next version.
> 
> Anything i can do to contribute to this ?

Hi, I took closer look to UTAM json. All jsons in **salesforce-pageobjects** lib represents pages and load method loads pages. Playwright-elements is a tool to build complex web components not pages, it even allows not to use page object at all. So I think that page object loader for playwright should be standalone solution. In case I will add such function to playwright elements it will be able to create web elements based on selectors from json files but I will not be able to add page object methods to classes because this lib do not designed to inject methods to page object.

**Comment by PavanMudigondaTR** [comment]
@DanteUkraine  I agree playwright page object loader for salesforce should be standalone solution. Do you have any rough idea to create new solution ?

**Comment by DanteUkraine** [comment]
@PavanMudigondaTR Unfortunately no, you can take a look to wdio load method implementation, general approach to parse json and build methods should be similar. I will close this issue. Thanks.

**Comment by DanteUkraine** [comment]
Closing this feature request.
